/**:
  ros__parameters:
    image_transport: raw
    family: 'Standard52h13'
    size: 0.10
    z_up: false
    max_hamming: 2
    detector:
      threads: 4
      decimate: 2.0
      blur: 0.0
      sharpening: 0.25
    tag:
      ids: [0]
      frames: [bin_tag_link]
      sizes: [0.10]