---
/**:
  ros__parameters:
    image_transport: raw
    family: 'Standard52h13'
    size: 0.055
    profile: false
    max_hamming: 1
    publish_tf: true
    detector:
      threads: 4
      decimate: 2.0
      blur: 0.4
      refine: true
      sharpening: 0.25
      debug: false
    tag:
      ids: [0]
      frames: [bin_tag_link]
      sizes: [0.10]